---
# role: quadlet
# file: tasks/container.yml

- name: "QUADLET | Ensure container directories exist"
  ansible.builtin.file:
    path: "{{ __quadlet_directory.path }}"
    owner: "{{ __quadlet_directory.owner }}"
    group: "{{ __quadlet_user.name }}"
    mode: "0750"
    state: directory
  loop:
    - path: "{{ quadlet_base_dir }}/{{ __quadlet_container.name }}"
      owner: root
    - path: "{{ __quadlet_container.environment_file | dirname }}"
      owner: root
    - path: "{{ quadlet_base_dir }}/{{ __quadlet_container.name }}/data"
      owner: "{{ __quadlet_user.name }}"
  loop_control:
    loop_var: __quadlet_directory
    label: "{{ __quadlet_directory.path }}"

- name: "QUADLET | Render container environment file"
  ansible.builtin.template:
    src: environment.env.j2
    dest: "{{ __quadlet_container.environment_file }}"
    owner: root
    group: "{{ __quadlet_user.name }}"
    mode: "0640"
  notify: "restart user services"

- name: "QUADLET | Manage rootless Podman secrets"
  become: true
  become_user: "{{ __quadlet_user.name }}"
  containers.podman.podman_secret:
    name: "{{ __quadlet_secret.name }}"
    data: "{{ __quadlet_secret.value | default(omit) }}"
    path: "{{ __quadlet_secret.value_file | default(omit) }}"
    state: present
  environment: "{{ __quadlet_user_systemd_env }}"
  loop: "{{ __quadlet_container.secrets }}"
  loop_control:
    loop_var: __quadlet_secret
    label: "{{ __quadlet_secret.name }}"
  no_log: true
  notify: "restart user services"

- name: "QUADLET | Render root-owned user Quadlet"
  ansible.builtin.template:
    src: container.container.j2
    dest: "/etc/containers/systemd/users/{{ __quadlet_service_user.uid }}/{{ __quadlet_container.name }}.container"
    owner: root
    group: root
    mode: "0644"
  notify:
    - "reload user manager"
    - "restart user services"
