---
# role: quadlet
# file: tasks/main.yml

- name: "QUADLET | Install packages"
  ansible.builtin.package:
    name: "{{ __quadlet_packages }}"
    state: present

- name: "QUADLET | Manage service users"
  ansible.builtin.include_tasks: user.yml
  loop: "{{ quadlet_users }}"
  loop_control:
    loop_var: __quadlet_user
    label: "{{ __quadlet_user.name }}"
