---
# role: quadlet
# file: tasks/pod.yml

- name: "QUADLET | Render root-owned user pod Quadlet"
  ansible.builtin.template:
    src: pod.pod.j2
    dest: "/etc/containers/systemd/users/{{ __quadlet_user_uid }}/{{ __quadlet_pod.name }}.pod"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ __quadlet_user.pods | default([]) }}"
  loop_control:
    loop_var: __quadlet_pod
    label: "{{ __quadlet_pod.name }}"
  notify:
    - "QUADLET | Reload user manager"
    - "QUADLET | Restart user services"
