---
# role: quadlet
# file: tasks/user.yml

- name: "QUADLET | Ensure service group exists"
  ansible.builtin.group:
    name: "{{ __quadlet_user.name }}"
    system: true
    state: present

- name: "QUADLET | Create service user with subordinate IDs"
  ansible.builtin.command:
    cmd: >-
      useradd --system --add-subids-for-system --gid {{ __quadlet_user.name }}
      {{ '--uid ' ~ __quadlet_user.uid if __quadlet_user.uid is defined else '' }}
      {{ __quadlet_user.name }}
  register: __quadlet_useradd
  changed_when: __quadlet_useradd.rc == 0
  failed_when: __quadlet_useradd.rc not in [0, 9]

- name: "QUADLET | Manage service user"
  ansible.builtin.user:
    name: "{{ __quadlet_user.name }}"
    uid: "{{ __quadlet_user.uid | default(omit) }}"
    home: "{{ __quadlet_user.home | default('/var/lib/' ~ __quadlet_user.name) }}"
    shell: "{{ __quadlet_user.shell | default('/usr/sbin/nologin') }}"
    group: "{{ __quadlet_user.name }}"
    create_home: true
    state: present
  register: __quadlet_service_user

- name: "QUADLET | Initialize service user state"
  ansible.builtin.set_fact:
    __quadlet_handler_user: "{{ __quadlet_user }}"
    __quadlet_user_systemd_env:
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ __quadlet_service_user.uid }}/bus"
      HOME: "{{ __quadlet_user.home | default('/var/lib/' ~ __quadlet_user.name) }}"
      XDG_RUNTIME_DIR: "/run/user/{{ __quadlet_service_user.uid }}"

- name: "QUADLET | Ensure rootless user Quadlet directories exist"
  ansible.builtin.file:
    path: "{{ __quadlet_directory }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop:
    - /etc/containers/systemd/users
    - "/etc/containers/systemd/users/{{ __quadlet_service_user.uid }}"
  loop_control:
    loop_var: __quadlet_directory

- name: "QUADLET | Enable linger for service user"
  ansible.builtin.command:
    argv:
      - loginctl
      - enable-linger
      - "{{ __quadlet_user.name }}"
    creates: "/var/lib/systemd/linger/{{ __quadlet_user.name }}"

- name: "QUADLET | Ensure user manager is running"
  ansible.builtin.systemd_service:
    name: "user@{{ __quadlet_service_user.uid }}.service"
    state: started

- name: "QUADLET | Render user pods"
  ansible.builtin.import_tasks: pod.yml

- name: "QUADLET | Render containers for service user"
  ansible.builtin.include_tasks: container.yml
  loop: "{{ __quadlet_user.containers | default([]) }}"
  loop_control:
    loop_var: __quadlet_container
    label: "{{ __quadlet_container.name }}"

- name: "QUADLET | Apply user service changes"
  ansible.builtin.meta: flush_handlers

- name: "QUADLET | Manage user services"
  ansible.builtin.import_tasks: service.yml
