---
# role: quadlet
# file: molecule/default/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        quadlet_users:
          - name: "quadlet_vikunja"
            uid: 901
            pods:
              - name: "vikunja"
                ports:
                  - "127.0.0.1:3456:3456"
                networks:
                  - "pasta"
                enabled: false
                state: "created"
            containers:
              - name: "vikunja"
                image: "localhost/vikunja:test"
                container_name: "vikunja"
                pod: "vikunja"
                environment:
                  VIKUNJA_DATABASE_TYPE: "postgres"
                  VIKUNJA_DATABASE_PASSWORD_FILE: "/run/secrets/vikunja_db_password"
                  VIKUNJA_SERVICE_SECRET_FILE: "/run/secrets/vikunja_service_secret"
                secrets:
                  - name: "vikunja_db_password"
                  - name: "vikunja_service_secret"
                volumes:
                  - "/srv/containers/vikunja/data:/app/vikunja/files:Z"
                enabled: false
                state: "created"
          - name: "quadlet_vaultwarden"
            uid: 902
            containers:
              - name: "vaultwarden"
                image: "localhost/vaultwarden:test"
                container_name: "vaultwarden"
                environment:
                  DOMAIN: "http://vaultwarden.example.invalid"
                  SIGNUPS_ALLOWED: "false"
                secrets:
                  - name: "vaultwarden_admin_token"
                    type: "env"
                    env_target: "ADMIN_TOKEN"
                volumes:
                  - "/srv/containers/vaultwarden/data:/data:Z"
                ports:
                  - "127.0.0.1:8080:80"
                exec_start_pre:
                  - "/bin/bash -c 'until pg_isready -h POSTGRES_PUBLIC_IP -p 5432 -U vaultwarden; do sleep 10; done;'"
                restart_policy: "on-failure"
                restart_sec: "10s"
                timeout_start_sec: 300
                enabled: false
                state: "created"
verifier:
  name: "ansible"
scenario:
  name: "default"
platforms:
  - name: "quadlet"
    image: "docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}"
    pre_build_image: true
    override_command: false
    systemd: true
